import type { Metadata } from "next";
import localFont from "next/font/local";
import "antd/dist/reset.css";
import "./globals.css";
import Header from '../components/header'

import Footer from '../components/footer'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-col justify-center items-center p-4 sm:p-2 md:p-4  bg-green-100  ">
          <Header />
        </header >
        {children}
        <footer className="flex flex-col justify-center items-center p-4 sm:p-2 md:p-4  bg-green-100  ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
